# Generated by Django 5.1.7 on 2025-04-03 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_user_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bio',
            new_name='Bio',
        ),
    ]
