# Generated by Django 5.1.7 on 2025-04-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_user_birthday_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Phone',
            field=models.CharField(default='911', max_length=15, null=True),
        ),
    ]
