# Generated by Django 5.1.7 on 2025-04-18 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0007_alter_profile_image_alter_profile_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
