# Generated by Django 5.1.7 on 2025-04-18 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0010_alter_profile_image_alter_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Gender',
        ),
    ]
