# Generated by Django 5.1.7 on 2025-04-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0012_user_bio_user_birthday_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, default='ABC', max_length=200, null=True),
        ),
    ]
