# Generated by Django 5.1.7 on 2025-04-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0013_alter_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='City',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
