# Generated by Django 5.1.7 on 2025-04-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0014_user_address_user_city_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Phone',
            field=models.CharField(default='0000000000', max_length=15, null=True),
        ),
    ]
