# Generated by Django 5.1.7 on 2025-03-31 05:29

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Discount', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='discount', unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Desc', models.TextField(blank=True, default='This is the discount', null=True)),
                ('Discount_Percent', models.DecimalField(decimal_places=2, default='0.1', max_digits=10)),
                ('Active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Discounts',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Payment', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=20, prefix='payment', unique=True)),
                ('Desc', models.TextField(blank=True, default='This is the product', null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Method', models.CharField(max_length=100)),
                ('Money', models.DecimalField(decimal_places=2, default='1.99', max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Payment',
            },
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Product_Category', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='ven', unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Desc', models.TextField(blank=True, default='This is the discount', null=True)),
                ('Image', models.ImageField(default='category.jpg', upload_to='category')),
            ],
            options={
                'verbose_name_plural': 'Product_Categories',
            },
        ),
        migrations.CreateModel(
            name='Product_Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Product_Inventory', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='product_inventory', unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('Updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Product_Inventories',
            },
        ),
        migrations.CreateModel(
            name='Order_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Order_Detail', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='order_detail', unique=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Total_Price', models.DecimalField(decimal_places=2, default='1.99', max_digits=10)),
                ('Payment_Status', models.BooleanField(default=False)),
                ('Delivery_Status', models.CharField(choices=[('process', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='process', max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.payment')),
            ],
            options={
                'verbose_name_plural': 'Order_Detail',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Product', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='product', unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Desc', models.TextField(blank=True, default='This is the product', null=True)),
                ('Price', models.DecimalField(decimal_places=2, default='1.99', max_digits=10)),
                ('Discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.discount')),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product_category')),
                ('Inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product_inventory')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=1)),
                ('Note', models.TextField(blank=True, default='.....', null=True)),
                ('image', models.CharField(max_length=200)),
                ('order_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.order_detail')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
            ],
            options={
                'verbose_name_plural': 'Order_Items',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='product.jpg', upload_to='product-image')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
            ],
        ),
    ]
