# Generated by Django 5.1.7 on 2025-04-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_discount_id_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit_Card'), ('bank_transfers', 'Bank_Transfers')], max_length=100),
        ),
    ]
