# Generated by Django 5.1.7 on 2025-04-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tags',
            new_name='Tags',
        ),
    ]
