# Generated by Django 5.1.7 on 2025-04-02 18:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_tags_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='This is the product', null=True),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='Desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='This is the discount', null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='Review',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
