# Generated by Django 5.1.7 on 2025-04-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_product_desc_alter_product_category_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Rating',
            field=models.IntegerField(blank=True, choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], null=True),
        ),
    ]
