# Generated by Django 5.1.7 on 2025-04-03 07:20

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_productreview_id_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='ID_ProductReview',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='REVIEW', unique=True),
        ),
    ]
