# Generated by Django 5.1.7 on 2025-04-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_staff_first_name_remove_staff_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='Phone',
        ),
    ]
