# Generated by Django 5.1.7 on 2025-04-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_address_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Address1',
            new_name='Address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Address2',
        ),
    ]
