# Generated by Django 5.1.7 on 2025-04-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_discount_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='Image',
            field=models.ImageField(blank=True, default='campaign.jpg', null=True, upload_to='campaign-image'),
        ),
    ]
