# Generated by Django 5.1.7 on 2025-04-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_discount_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='Image',
            field=models.ImageField(null=True, upload_to='campaign-image'),
        ),
    ]
