# Generated by Django 5.1.7 on 2025-04-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_discount_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_inventory',
            name='Unit',
            field=models.CharField(default='Kilogram', max_length=100),
        ),
    ]
