# Generated by Django 5.1.7 on 2025-04-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_product_inventory_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='Note',
        ),
        migrations.AddField(
            model_name='order_detail',
            name='Note',
            field=models.TextField(blank=True, default='.....', null=True),
        ),
    ]
