# Generated by Django 5.1.7 on 2025-04-17 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_order_item_note_order_detail_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='Image',
        ),
    ]
