# Generated by Django 5.1.7 on 2025-04-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_order_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='Note',
            field=models.TextField(blank=True, default='Nothing', null=True),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='Total_Price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit_Card'), ('bank_transfers', 'Bank_Transfers')], default='cash', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Money',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
        ),
    ]
