# Generated by Django 5.1.7 on 2025-04-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Method',
            field=models.CharField(choices=[('pay_on_delivery', 'Pay On Delivery'), ('paypal', 'Paypal'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=100),
        ),
    ]
