# Generated by Django 5.1.7 on 2025-04-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Method',
            field=models.CharField(choices=[('pay_on_delivery', 'Pay On Delivery'), ('paypal', 'Paypal'), ('bank_transfer', 'Bank Transfer')], default='No', max_length=100),
        ),
    ]
