# Generated by Django 5.1.7 on 2025-04-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Method',
            field=models.CharField(choices=[('Pay_on_Delivery', 'Pay On Delivery'), ('Paypal', 'Paypal'), ('Bank_Transfer', 'Bank Transfer')], default='No', max_length=100),
        ),
    ]
