# Generated by Django 5.1.7 on 2025-04-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_payment_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
