# Generated by Django 5.1.7 on 2025-04-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_delete_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
