# Generated by Django 5.1.7 on 2025-04-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_order_detail_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Cost',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
        ),
    ]
