# Generated by Django 5.1.7 on 2025-04-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='active',
            new_name='Active',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='code',
            new_name='Code',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount',
        ),
        migrations.AddField(
            model_name='coupon',
            name='Discount',
            field=models.DecimalField(decimal_places=2, default='0.1', max_digits=10),
        ),
    ]
