# Generated by Django 5.1.7 on 2025-05-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_rename_active_coupon_active_rename_code_coupon_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='Name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20),
        ),
    ]
