# Generated by Django 5.1.7 on 2025-05-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_order_detail_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_inventory',
            name='Updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
