# Generated by Django 5.1.7 on 2025-04-02 09:20

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_payment_order_detail_payment_staff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='ID_Discount',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='DISCOUNT', unique=True),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='ID_Order_Detail',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='ORDER', unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Desc',
            field=models.TextField(blank=True, default='This is the payment', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ID_Payment',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=20, prefix='PAY', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ID_Product',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='P', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='core.product_category'),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='ID_Product_Category',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='CAT', unique=True),
        ),
        migrations.AlterField(
            model_name='product_inventory',
            name='ID_Product_Inventory',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='INVENTORY', unique=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='ID_Salary',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='SALARY', unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='ID_Staff',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='STAFF', unique=True),
        ),
    ]
