# Generated by Django 5.1.7 on 2025-04-03 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_productreview_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='First_Name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='Last_Name',
        ),
    ]
